cart/urls.py
from django.urls import path

from . views import (
    in_cart_add,
    cart_add, 
    user_order,
    business_detail,
    cart_detail, 
    cart_remove
)

app_name = 'cart'

urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('business_detail/', business_detail, name='business_detail'),
    path('current_orders/', user_order, name='user_order'),
    path('current_orders/<int:order_id>/', user_order, name='user_order_special'),
    path('add/<int:product_id>', in_cart_add, name='in_cart_add'),
    path('add/<int:product_id>/<str:category_slug>', cart_add, name='cart_add'),
    path('remove/<int:product_id>/', cart_remove, name='cart_remove'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

admin.site.site_header = 'Модуль администратора СБЕР кафе'
admin.site.index_title = 'Модуль администратора'
admin.site.site_title = 'СБЕР кафе'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('staff/', include('staff.urls')),
    path('', include('shop.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.contrib import admin
from django.urls import path

from shop.views import (
    product_list, 
    product_detail,
    about_us,
    lunch,
    lunch_products, 
    logout_view,
    comment_add,
    get_table,
    tables_by_time,
)
from .views import *

app_name = 'shop'

urlpatterns = [
    path('', product_list, name='product_list'),
    path('logout/', logout_view, name='logout_view'),
    path('lunch/<int:day>/', lunch, name="lunch"),
    path('lunch_products/', lunch_products, name="lunch_products"),
    path('about_us/', about_us, name='about_us'),
    path('print_us/', print_us, name='print_us'),
    path('get_table/', get_table, name='get_table'),
    path('tables_by_time/', tables_by_time, name=''),
    path('<str:category_slug>/<int:week>', product_list, name='product_list_by_category'),
    path('<int:id>/<str:slug>/', product_detail, name='product_detail'),
    path('comment/<int:product_id>/<str:username>/', comment_add, name='comment_view'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 26)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(label="", choices=PRODUCT_QUANTITY_CHOICES, coerce=int, widget=forms.Select(attrs={'class': 'form-control'}))
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from django.contrib import messages
from django.urls import reverse
from datetime import datetime, timedelta
from shop.models import Product, Cafeteria, Table, TableTime
from users.models import Profile
from orders.models import Order, OrderItem
from .cart import Cart
from .forms import CartAddProductForm
from django.template.defaultfilters import slugify
from config.views import get_natural_range
from django import template

@require_POST
def in_cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
    return redirect('cart:cart_detail')

@require_POST
def cart_add(request, product_id, category_slug=None):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
    return redirect(reverse('shop:product_list_by_category', kwargs={'category_slug': category_slug, 'week': 1}))


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    messages.success(request, 'Удалено')
    return redirect('cart:cart_detail')


    
def cart_detail(request):
    cart = Cart(request)
    cafeteria = Cafeteria.objects.get(id=3)
    tables = Table.objects.filter(cafeteria_id=3)  # ОТОБРАЖЕНИЕ ТЕКУЩЕЙ КАФЕТЕРИИ TODO
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'update': True})
    context = {'cart': cart, 'cafeteria': cafeteria, 'tables': tables,
                'time_periods': get_time_segments(),}
    return render(request, 'cart/detail.html', context)


def business_detail(request):
    ids = [13, 15, 17, 29]
    cart = Product.objects.filter(id__in=ids) # ОТОБРАЖЕНИЕ ТЕКУЩЕЙ КАФЕТЕРИИ TODO
    cafeteria = Cafeteria.objects.get(id=3)
    tables = Table.objects.filter(cafeteria_id=3)  # ОТОБРАЖЕНИЕ ТЕКУЩЕЙ КАФЕТЕРИИ TODO
    context = {'cart': cart, 'cafeteria': cafeteria, 'tables': tables,
                'time_periods': get_time_segments(), 'business': True}
    return render(request, 'cart/business_detail.html', context)


def get_time_segments():
    current_time = datetime.now()
    hours = current_time.hour
    minutes = current_time.minute
    time_segments = []

    while hours != 0 or minutes != 0:
        time_segments.append(f"{hours:02d}:{minutes:02d}")
        if minutes < 30:
            minutes = 30
        else:
            minutes = 0
            hours = (hours + 1) % 24
    return time_segments[2:]


def user_order(request, order_id=0):
    orders_before = 0
    profile = Profile.objects.get(email=request.user.email)
    all_orders = Order.objects.filter(profile_id=profile.id)
    current_table = None
    if not order_id:
        order = Order.objects.filter(profile_id=profile.id).first()
    else:
        order = Order.objects.get(id=order_id)
    if order is None:
        order_items = None
        return render(request, 'cart/user_order.html', {'order': order})
    else:
        if order.in_cafe:
            current_table = order.table
        orders_before = Order.objects.filter(reserve_time=order.reserve_time, id__lt=order.id).count() + 1
        order_items = OrderItem.objects.filter(order_id=order.id)
    cafeteria = Cafeteria.objects.get(id=3)
    tables = Table.objects.filter(cafeteria_id=3)  # ОТОБРАЖЕНИЕ ТЕКУЩЕЙ КАФЕТЕРИИ TODO
    context = {'order_items': order_items, 'order': order, 'all_orders': all_orders, 'orders_before': orders_before,
               'cafeteria': cafeteria, 'tables': tables, 'current_table': current_table, 'profile': profile}
    return render(request, 'cart/user_order.html', context)

cart/templates/cart/business_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container">
    <div id="content" class="container">
    <div class="album">
      <div class="container">
        <span class="badge pull-right">
          {% with total_items=cart|length %}
            {% if total_items > 0 %}
                <div class="current-cart-items-title">
                    Список позиций ланча:
                </div>
              {% else %}
              <div class="current-cart-items-title">
                Список позиций ланча:
                  </div>
              {% endif %}
          {% endwith %}
        </span> 
        <table class="table">
          <thead>
          <tr>
            <th scope="col">Изображение</th>
            <th scope="col">Товар в ланче</th>
          </tr>
          </thead>
          <tbody>
            {% for product in cart %}
                <tr>
                  <th scope="row">
                    <img src="{% if product.image %} {{ product.image.url }} {% else %} {% static 'img/default.jpg' %} {% endif %}" alt="..." style="height: 130px; width: auto">
                  </th>
                  <td>{{ product.name }}</td>
                </tr>
            {% endfor %}
            <tr>
              <td><b>Суммарная стоимость ланча:</b></td>
              <td colspan="4"></td>
              <td colspan="num"><b> 249 ₽</b></td>
            </tr>
          </tbody>
        </table>
       </div>
    </div>

    <div class="row">
      <div class="col p-2">
        <a class="btn btn-outline-warning btn-block btn-lg"  data-bs-toggle="modal"
        data-bs-target="#orderConfirm" id="businessConfirm-btn">Оформить заказ</a>
      </div>
      {% include 'orders\order\create.html'%}
    </div>
  </div>
</div>
{% endblock %}

cart/templates/cart/detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container">
    <div id="content" class="container">
    <div class="album">
      <div class="container">
        <span class="badge pull-right">
          {% with total_items=cart|length %}
            {% if total_items > 0 %}
                  <div class="current-cart-items-title">
                      Текущий список позиций:
                  </div>
              {% else %}
              <div class="current-cart-items-title">
                      Текущий список позиций:
                  </div>
                  Вы пока ничего не выбрали...
              {% endif %}
          {% endwith %}
        </span> 
        <table class="table">
          <thead>
          <tr>
            <th scope="col">Изображение</th>
            <th scope="col">Товар</th>
            <th scope="col">Кол-во</th>
            <th scope="col">Удалить</th>
            <th scope="col">Цена одного товара</th>
            <th scope="col">Сумма</th>
          </tr>
          </thead>
          <tbody>
            {% for item in cart %}
              {% with product=item.product  %}
                <tr>
                  <th scope="row">
                    <a href="{{ product.get__absolute_url }}">
                      <img src="{% if product.image %} {{ product.image.url }} {% else %} {% static 'img/default.jpg' %} {% endif %}" alt="..." style="height: 130px; width: auto">
                    </a>
                  </th>
                  <td>{{ product.name }}</td>
                  <td>
                  <form action="{% url "cart:in_cart_add" product.id %}" method="post">
                    {% csrf_token %}
                    <span style="display:inline-block">    
                      {{ item.update_quantity_form.quantity }}
                      {{ item.update_quantity_form.update }}
                      <input type="submit" value="Изменить" class="btn btn-outline-success" style="margin-top:10%; white-space: pre-line;">
                    </span>
                  </form>
                  </td>
                  <td>
                    <a href="{% url "cart:cart_remove" product.id %}" style="width: 100%; font-size: 10pt;" 
                    class="btn btn-outline-danger btn-block btn-lg">Удалить</a>
                  </td>
                  <td> {{ item.price }} ₽</td>
                  <td> {{ item.total_price }} ₽</td>
                </tr>
              {% endwith %}
            {% endfor %}
            <tr>
              <td><b>Суммарная стоимость:</b></td>
              <td colspan="4"></td>
              <td colspan="num"><b> {{ cart.get_total_price }} ₽</b></td>
            </tr>
          </tbody>
        </table>
       </div>
    </div>
        
    <div class="row">
      <div class="col p-2">
          <a href="{% url "shop:product_list" %}" class="btn btn-outline-success btn-block btn-lg">Добавить еще</a>
      </div>
    </div>
    {% if cart|length > 0 %}
      <div class="row">
        <div class="col p-2">
          <a class="btn btn-outline-warning btn-block btn-lg"  data-bs-toggle="modal"
          data-bs-target="#orderConfirm" id="orderConfirm--btn">Оформить заказ</a>
        </div>
        {% include 'orders\order\create.html'%}
      </div>
    {% endif %}
  </div>
</div>
{% endblock %}

cart/templates/cart/user_order.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container">

  <div id="content">
    <div class="album">

      {% if order is not None %}
        <span class="badge pull-right">
          <div class="current-cart-items-title">
            Заказ №{{order.id}}:
            <a class="btn btn-info btn-block" id="orderSelection" data-bs-toggle="dropdown" aria-expanded="false" href="{{ order.get_absolute_url }}">
              <div class="check-title">Выбрать заказ:</div>
            </a>
            <selection class="dropdown-menu" id="orderDropdown" name="orderDropdown">
              {% for ord in all_orders %}
                <li><a class="dropdown-item" href="{{ ord.get_absolute_url }}">Заказ №{{ord.id}}</a></li>
              {% endfor %}
            </selection>
          </div>
        </span>
        <table class="table">
          <thead>
            <tr>
              <th scope="col">Изображение</th>
              <th scope="col">Товар</th>
              <th scope="col">Кол-во</th>
              <th scope="col">Цена одного товара</th>
              <th scope="col">Сумма</th>
            </tr>
          </thead>
          <tbody>
            {% for item in order_items %}
              {% with product=item.product %}
                <tr class="headings">
                  <th scope="row">
                    <img src="{% if product.image %} {{ product.image.url }} {% else %} {% static 'img/default.jpg' %} {% endif %}"
                    alt="..." style="height: 130px; width: auto">
                  </th>
                  <td>{{ product.name }}</td>
                  <td> {{ item.quantity }} шт.</td>
                  <td> {{ item.price }} ₽</td>
                  <td> {{ item.get_cost }} ₽</td>
                </tr>
              {% endwith %}
            {% endfor %}
            <tr>
              <td><b>Суммарная стоимость</b></td>
              <td colspan="3"></td>
              <td colspan="num"><b> {{ order.get_total_cost }} ₽</b></td>
            </tr>
          </tbody>
        </table>
      {% else %}
        <span class="badge pull-right">
          <div class="current-cart-items-title">
            Заказов нет
        </span>
      {% endif %}
    </div>
    {% if order is not None %}
    <div class="card-body" style="display: flex;
    flex-wrap: wrap; justify-content: center; align-items: center;">
      <div class="card" style="width: 300 px; margin-bottom: 10px; margin-top: 20px;">
          <img src="/media/qr/{{ order.id }}.png" class="card-img-top" style="height: 300px; width: 300px;" alt="...">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">Статус заказа: {% if order.ready %} Готов! {% else %} Не готов {% endif %}</li>
            {% if not order.ready and orders_before %}<li class="list-group-item">Ваш заказ в очереди: {{orders_before}}</li> {% endif %}
            {% if order.in_cafe %}<li class="list-group-item">Вы выбрали стол: №{{current_table.number}}</li>
            <li class="list-group-item">Бронь с: {{order.reserve_time}}</li>
            {% endif %}
          </ul>
      </div>
      {% endif %}
      
    </div>
  </div>
  <div class="row">
    <div class="col p-2">
      <a href="{% url 'shop:product_list' %}" class="btn btn-outline-success btn-block btn-lg">Заказать еще</a>
    </div>
  </div>
</div>
{% endblock %}