cart/urls.py
from django.urls import path

from . views import (
    in_cart_add,
    cart_add, 
    user_order,
    business_detail,
    cart_detail, 
    cart_remove
)

app_name = 'cart'

urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('business_detail/', business_detail, name='business_detail'),
    path('current_orders/', user_order, name='user_order'),
    path('current_orders/<int:order_id>/', user_order, name='user_order_special'),
    path('add/<int:product_id>', in_cart_add, name='in_cart_add'),
    path('add/<int:product_id>/<str:category_slug>', cart_add, name='cart_add'),
    path('remove/<int:product_id>/', cart_remove, name='cart_remove'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

admin.site.site_header = 'Модуль администратора СБЕР кафе'
admin.site.index_title = 'Модуль администратора'
admin.site.site_title = 'СБЕР кафе'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('staff/', include('staff.urls')),
    path('', include('shop.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.contrib import admin
from django.urls import path

from shop.views import (
    product_list, 
    product_detail,
    about_us,
    lunch,
    lunch_products, 
    logout_view,
    comment_add,
    get_table,
    tables_by_time,
)
from .views import *

app_name = 'shop'

urlpatterns = [
    path('', product_list, name='product_list'),
    path('logout/', logout_view, name='logout_view'),
    path('lunch/<int:day>/', lunch, name="lunch"),
    path('lunch_products/', lunch_products, name="lunch_products"),
    path('about_us/', about_us, name='about_us'),
    path('print_us/', print_us, name='print_us'),
    path('get_table/', get_table, name='get_table'),
    path('tables_by_time/', tables_by_time, name=''),
    path('<str:category_slug>/<int:week>', product_list, name='product_list_by_category'),
    path('<int:id>/<str:slug>/', product_detail, name='product_detail'),
    path('comment/<int:product_id>/<str:username>/', comment_add, name='comment_view'),
]

shop/forms.py
from shop.models import Comment, StarRating, Product, CommentManage
from django.db import models
from django import forms
from django.forms import (ModelForm, TextInput, DateTimeInput, 
                          PasswordInput, EmailInput)


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ["user", "product", "star_rating", "description", "taste_rating", "price_rating", "representability_rating"]


class StarRatingForm(ModelForm):
    class Meta:
        model = StarRating
        fields = ["star_1", "star_2", "star_3", "star_4", "star_5", "product"]


class ProductStarRatingUpdateForm(ModelForm):
    class Meta:
        model = Product
        fields = ['star_rating']


class CommentManageForm(ModelForm):
    class Meta:
        model = CommentManage
        fields = ['id', 'user', 'description']
        labels = {
            'user': 'Пользователь',
            'description': 'Сообщения',
        }

shop/views.py
import datetime
import json
from django.forms.models import model_to_dict
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_POST
from django.contrib.auth import logout
from .models import Category, Product, StarRating, Comment, LunchPosition, CommentManage
from cart.cart import Cart
from staff.models import Staff
from .forms import CommentForm, StarRatingForm, ProductStarRatingUpdateForm, CommentManageForm
from cart.forms import CartAddProductForm
from users.views import user_registration
from users.forms import LoginForm, RegistrationForm
from decimal import Decimal, ROUND_HALF_UP
from django import template
from config.views import get_natural_range
from django.http import JsonResponse
from .models import Cafeteria, Table, TableTime
from django.views.decorators.http import require_GET


def product_list(request, category_slug=None, week=1):
    staff_id = 4
    try:
        staff_id = Staff.objects.get(user_id=request.user.id).staff_id
    except:
        pass
    login_error = ""
    registration_error = ""
    if request.method == "POST":
        errors = user_registration(request)
        login_error, registration_error = errors["login_error"], errors["registration_error"]
    registration_form = RegistrationForm()
    login_form = LoginForm()
    category = None
    week_url = '/all/'
    comments = Comment.objects.exclude(description="")
    categories = Category.objects.all().order_by('-created_at')
    products = Product.objects.filter(available=True) & Product.objects.filter(week=week)
    if category_slug and category_slug != 'all':
        week_url = '/' + category_slug + '/'
        category = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(category=category) & Product.objects.filter(week=week)

    today = datetime.date.today()
    dayOfWeek = today.weekday()

    lastTuesday = (today - datetime.timedelta(days=dayOfWeek-1)).strftime('%Y-%m-%d').replace('-', '.')
    nextTuesday = (today + datetime.timedelta(days=7-dayOfWeek)).strftime('%Y-%m-%d').replace('-', '.')
    nextnextTuesday = (today + datetime.timedelta(days=14-dayOfWeek)).strftime('%Y-%m-%d').replace('-', '.')
    if category_slug is None:
        category_slug = 'all'
    context = {
        'form_dict': {
            'login_form': login_form,
            'registration_form': registration_form,
        },
        'category': category,
        'category_slug': category_slug,
        'categories': categories,
        'products': products,
        'login_error': login_error,
        'registration_error': registration_error,
        'week_url': week_url,
        'comments': comments,
        'week': week,
        'tuesdays': {'last': lastTuesday, 'next': nextTuesday, 'nextnext': nextnextTuesday,} ,
        'staff_id': staff_id,
    }

    return render(request, 'shop/product/list.html', context)


def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    context = {
        'product': product,
        'cart_product_form': cart_product_form
    }
    return render(request, 'shop/product/detail.html', context)


def get_lunch_dates():
    dates = []
    today = datetime.datetime.today().date()
    for i in range(14):
        dates.append(today + datetime.timedelta(days=i))
    return dates


def lunch(request, day=1):
    deserts = LunchPosition.objects.filter(category_id=9).filter(day=day)
    salads = LunchPosition.objects.filter(category_id=8).filter(day=day)
    garnishes = LunchPosition.objects.filter(category_id=7).filter(day=day)
    soups = LunchPosition.objects.filter(category_id=6).filter(day=day)
    drinks = LunchPosition.objects.filter(category_id=5).filter(day=day)
    dates = get_lunch_dates()
    context = {
        "categories": [["Салат", salads], ["Суп", soups], ["Гарнир", garnishes], ["Десерт", deserts], ["Напиток", drinks]],
        "dates":  [[ind + 1, el] for ind, el in enumerate(dates)],
        'day': day, "cur_date": datetime.datetime.today().date() + datetime.timedelta(days=day - 1),
    }

    return render(request, 'shop/product/lunch.html', context)


def lunch_products(request): # TODO
    cart = Cart(request)
    if request.method == 'POST':
        data = json.loads(request.body)
        selected_positions = list(map(int, data['selectedPositions']))
        products = Product.objects.filter(id__in=selected_positions)
        for product in products:
            cart.add(product=product, quantity=1, update_quantity=False)
    return render(request, 'cart/detail.html', {})


def news(request):
    return render(request, 'shop/product/news.html')

@require_POST
def comment_add(request, product_id, username):
    data = request.POST
    product = get_object_or_404(Product, id=product_id)
    comment_data = {"user": username, "taste_rating": data['taste-rating'], "representability_rating": data['representability-rating'],
                    "price_rating": data['price-rating'], "description": data['comment-text'], "product": product_id}
    now_rating = StarRating.objects.filter(product_id=product_id)
    total_rating = 0
    average_rating = round((int(comment_data["price_rating"]) + int(comment_data["taste_rating"]) + int(comment_data["representability_rating"])) / 3)
    if now_rating.count():
        now_rating = StarRating.objects.get(product_id=product_id)
        rating_data = model_to_dict(now_rating, fields=[field.name for field in now_rating._meta.fields])
        user_comments = Comment.objects.filter(user=username, product_id=product_id)
        if user_comments.count():
            for com in user_comments:
                com_rating = com.star_rating
                rating_data[f'star_{str(com_rating)}'] -= 1
                com.delete()
        rating_data[f'star_{str(average_rating)}'] += 1
        rating_sum = 0
        rating_count = 0
        for key in rating_data.keys():
            if "star" in key:
                rating_sum += rating_data[key] * int(key.split("_")[1])
                rating_count += rating_data[key]
        total_rating = Decimal(rating_sum / rating_count).quantize(Decimal("0.01"), rounding=ROUND_HALF_UP)
        rating_form = StarRatingForm(rating_data, instance=now_rating)
        rating_form.save()
    else:
        rating_data = {"star_1": 0, "star_2": 0, "star_3": 0, "star_4": 0, "star_5": 0, "product": product_id}
        rating_data[f'star_{str(average_rating)}'] += 1
        total_rating = Decimal(average_rating).quantize(Decimal("0.01"), rounding=ROUND_HALF_UP)
        rating_form = StarRatingForm(rating_data)
        rating_form.save()
    comment_data["star_rating"] = average_rating
    comment_form = CommentForm(comment_data)
    comment_form.save()
    product_upd = ProductStarRatingUpdateForm({"star_rating": total_rating}, instance=product)
    product_upd.save()
    return redirect('shop:product_list')


@require_GET
def get_table(request):
    tableseatId = request.GET.get('seatId')
    try:
        table = Table.objects.get(id=tableseatId)
        data = {
            'number': table.number,
            'id': table.id,
        }
    except Table.DoesNotExist:
        data = {
            'number': "",
            'id': 0,
        }
    return JsonResponse(data)


@require_GET
def tables_by_time(request):
    selectedTime = request.GET.get('selectedTime')
    tables = Table.objects.filter(cafeteria_id=3)  # TODO
    table_times = TableTime.objects.filter(ordered_at=selectedTime)
    data = {'tables': []}
    for table in tables:
        if not table_times.filter(table_id=table.id):
            data['tables'].append('')
        else:
            data['tables'].append('occupied')
    return JsonResponse(data)


def logout_view(request):
    user_id = request.user.id
    try:
        staff = get_object_or_404(Staff, user_id=user_id)
        staff.logged = False
        staff.save()
    except:
        pass
    logout(request)
    return redirect('shop:product_list')

def about_us(request):
    return render(request, 'shop/product/about_us.html')

def print_us(request):
    if request.method == 'POST':
        form = CommentManageForm(request.POST)
        if form.is_valid():
            print(form.cleaned_data)
            form.save()
            return redirect('shop:about_us')
    else:
        # Если это GET-запрос, создайте форму без данных
        form = CommentManageForm()

    return render(request, 'shop/product/print_us.html', {'form': form})

def manage_us(request):
    #if not check_login(request):
      # return redirect(reverse("staff:login"))
    
    comments = CommentManage.objects.all()

    # Обработка отправки формы
def manage_us(request):
    comments = CommentManage.objects.all()

    if request.method == 'POST':
        form = CommentManageForm(request.POST)
        if form.is_valid():
            try:
                # Сохраняем комментарий в базе данных
                form.save()
                # Перенаправляем на страницу обзора комментариев
                return redirect('staff:manage_us')
            except Exception as e:
                # Обработка ошибки сохранения (можете настроить вывод в лог или отправку уведомления)
                print(f"Error saving comment: {e}")

    else:
        # Если это GET-запрос, создаем пустую форму
        instance = comments.first() if comments.exists() else None
        form = CommentManageForm(instance=instance)

    return render(request, 'staff/manage_us.html', {'comments': comments, 'form': form})

shop/templates/shop/product/list.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

<div class="container">
  <selection class="free-or-lunch">
    <a class="btn btn-light free-menu" href="{% url 'shop:product_list' %}">
      Свободное меню
    </a>
    <a class="btn btn-light free-menu" href="{% url 'shop:lunch' day=1%} ">
      Бизнес ланч
    </a>
  </selection>
  <selection class="week-choice">
    <a class="btn btn-outline-success m-2 {% if week == 1 %} active {% endif %}" href="{{ week_url }}1" id="first_week">
      На эту неделю
    </a>
    <label for="first_week">{{tuesdays.last}}-{{tuesdays.next}}</label>
    <a class="btn btn-outline-success m-2 {% if week == 2 %} active {% endif %}" href="{{ week_url }}2" id="second_week">
      На след. неделю
    </a>
    <label for="second_week">{{tuesdays.next}}-{{tuesdays.nextnext}}</label>
    <a class="btn btn-outline-success m-2 {% if week == 3 %} active {% endif %}" href="{{ week_url }}3" id="third_week">
      На послеслед. неделю
    </a>
    <label for="third_week">{{tuesdays.nextnext}}-...</label>
  </selection>
  <a href="/all/{{week}}" class="btn btn-light {% if category.slug is None %} active {% endif %}" style="margin: 5px;">
    <div class="main-menu-categories-title">Все</div>
  </a>
  {% for cat in categories %}
  <a href="/{{cat.slug}}/{{week}}" class="btn btn-light {% if cat.slug == category.slug %} active {% endif %}" style="margin: 5px;">
    <div class="main-menu-categories-title">{{ cat.name }}</div>
  </a>
  {% endfor %}
  <selection>
    <div class="food-map">
      <div class="cart-widget">
        {% with total_items=cart|length %}
        {% if user.is_authenticated %}
        {% if cart|length > 0 %}
        <a class="btn btn-outline-success btn-block btn-lg" style="margin-right: 10px;" href="{% url 'cart:cart_detail' %}" >
           <span class="cart-items-count">Корзина: {{ total_items }}</span>
        </a>
        {% else %}
        <a class="btn btn-outline-warning btn-block btn-lg" href="{% url 'cart:cart_detail' %}" style="margin-right: 10px;">
          <span class="cart-items-count">Корзина пуста</span>
        </a>
        {% endif %}
        <div class="second-week">
          <a class="btn btn-outline-success btn-block btn-lg" href="{% url 'cart:user_order' %}">
            <span class="cart-items-count">Заказы</span>
          </a>
        </div>
        {% endif %}
        {% endwith %}
    </div>
      <div id="buy-content">
          <div class="row">
            {% for product in products %}
            {% include 'shop\product\detail.html'%}
            {% include 'shop\product\more_about.html'%}
              <div class="col-md-4">
                <div class="card mb-4 shadow-sm">
                  <img class="card-img-top" src="{{product.image.url }}" style="--size: 250px; aspect-ratio: 1.00; width: var(--size); margin: auto; display: block;" alt="изображение продукта">
                  <div class="card-body">
                    <h5 class="card-title">{{product.name}}</h5>
                    <h6 class="card_price">{{product.price}} ₽</h6>
                  <button type="button" class="btn btn-success" data-bs-toggle="modal"
                    data-bs-target="#{{ product.slug }}-more-about-form" id="{{ product.slug }}-more-about-btn" ;>
                    <div class="user-login">Подробнее</div>
                  </button>
                  <button type="button" class="btn btn-success" data-bs-toggle="modal"
                    data-bs-target="#{{ product.slug }}--form" id="{{ product.slug }}-btn" ;>
                  <div class="user-login">+</div>
                    </button>
                  </div>
                </div>
              </div>
            {% endfor %}
          </div>
        </div>
    </div>
  </selection>
  <footer class="bg-body-tertiary text-center" style="margin-top: 50px;">
    <!-- Copyright -->
    <div class="text-center p-3">
      © СберКафе:
      <div class="text-body">Забайкальский край 2023</div>
    </div>
    <!-- Copyright -->
</footer>
</div>
{% endblock %}

shop/templates/shop/product/lunch.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

<div class="container">
  <selection class="free-or-lunch">
    <a class="btn btn-light free-menu" href="{% url 'shop:product_list' %}">
      Свободное меню
    </a>
    <a class="btn btn-light free-menu" href="{% url 'shop:lunch' day=1 %}">
      Бизнес ланч
    </a>
  </selection>
  <div class="current-cart-items-title">
    Бизнес-ланч  на {{cur_date}}
    <a class="btn btn-info btn-block" id="lunchDateSelection" data-bs-toggle="dropdown" aria-expanded="false" href="{% url 'shop:lunch' day=1 %}">
      <div class="check-title">Выбрать дату:</div>
    </a>
    <selection class="dropdown-menu" id="lunchDateDropdown" name="lunchDateDropdown">
      {% for ind, date in dates %}
        <li><a class="dropdown-item" href="{% url 'shop:lunch' day=ind %}">{{ date }}</a></li>
      {% endfor %}
    </selection>
  </div>
  <div class="row choice-soups">
    <script>
      function toggleActiveState(button) {
        console.log(button.getAttribute("data-id"));

        var row = button.closest('.row');
        var buttons = row.querySelectorAll('.btn-outline-success');
        buttons.forEach(function (btn) {
          btn.classList.remove('btn-active');
          btn.innerHTML = "Выбрать"
          button.value = 1
        });
        button.innerHTML = "Выбрано"
        button.classList.add('btn-active');
      }

      function addToCart(act) {
          const selectedPositions = document.querySelectorAll(".btn.btn-active");
          const positionsIndex = [...selectedPositions].map((pos) => {
            return pos.getAttribute("data-id");
          });
          const csrfToken = document.querySelector("[name=csrfmiddlewaretoken]").value;
          fetch("/lunch_products/", {
            method: "POST",
            headers: {
              "Content-Type": "application/json",
              "X-CSRFToken": csrfToken,
            },
            body: JSON.stringify({
              selectedPositions: positionsIndex,
            }),
          })
        }
    </script>


    <style>
      .btn-active {
        background-color: green;
        color: white;
      }
    </style>
    
    {% for name, category in categories %}
    <div class="row">
      {% for pos in category %}
      {% with product=pos.product %}
      {% include 'shop\product\more_about_lunch.html'%}
      <div class="col card mb-4 shadow-sm">
        <div class="name-category" style="font-size: 1.15rem; font-weight: 500; margin: 10px;">{{name}}</div>
        <img class="card-img-top" src="{{product.image.url }}"
          style="--size: 250px; aspect-ratio: 1.00; width: var(--size); margin: auto; display: block;"
          alt="изображение продукта">
        <div class="card-body">
         
          <h5 class="card-title">{{product.name}}</h5>
          <h6 class="card_price">{{product.price}} ₽</h6>
          <button type="button" class="btn btn-success" data-bs-toggle="modal"
            data-bs-target="#{{ product.slug }}-lunch-form" id="{{ product.slug }}-lunch-btn" ;>
            <div class="user-login">Подробнее</div>
          </button>
          {% if day == 1 %}
          <button type="button" class="btn btn-outline-success user-login" id="{{ product.slug }}" ;
            onclick="toggleActiveState(this)" data-id="{{product.id}}">
            Выбрать
          </button>
          {% endif %}
        </div>
      </div>
      {% endwith %}
      {% endfor %}
    </div>
    {% endfor %}
  </div>


  <div class="col p-2">
    {% if day == 1 %}
    {% if user.is_authenticated %}
    <form role="form" method="POST" action="{% url 'cart:business_detail' %}">
      {% csrf_token %}
      <button type="submit" onclick="addToCart()" class="btn btn-outline-success btn-block btn-lg" ;>
        <div>Добавить в корзину</div>
      </button>
    </form>
    {% else %}
    <button type="button" data-bs-toggle="modal" data-bs-target="#NotAuthorized" data-bs-dismiss="modal"
      class="btn btn-outline-success btn-block btn-lg" ;>
      <div>Добавить в корзину</div>
    </button>
    {% endif %}
    {% endif %}
  </div>




</div>
{% endblock %}

shop/templates/shop/product/more_about.html
{% load static %}
<div id="{{ product.slug }}-more-about-form" class="modal fade">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Подробнее</h4>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
      </div>
      <div class="modal-body">
        <div>
          <div class="row">
            <script>
              function increaseValue(inputId) {
                var currentValue = parseInt(document.getElementById(inputId).value);
                document.getElementById(inputId).value = currentValue + 1;
              }
          
              function decreaseValue(inputId) {
                var currentValue = parseInt(document.getElementById(inputId).value);
                if (currentValue > 1){
                document.getElementById(inputId).value = currentValue - 1;
                }
              }
            </script>

              <img src="{{ product.image.url }}" alt="" style="width: 100%">
              <div class="modal-name-of-product-title">{{ product.name }}
                {{product.star_rating}}
                <img src="{% static 'admin\img\star.svg' %}"/>
              </div>
              <div class="modal-cplc-title">
                {{ product.clpc }}
              </div>
              <h6 style="border: 0px; margin-bottom: 1px;">Цена</h6>
              <div class="modal-price-title">
                  {{ product.price }} ₽ 
              </div>
              <div class="modal-description-title">
                  {{ product.description | safe }}
              </div>
            <form action="{% url "cart:cart_add" product.id category_slug %}" method="post">
              {% csrf_token %}
              <div class="btn-cart-change-value-line">
                <button class="btn btn-success" onclick="decreaseValue('{{ product.slug }}-more');return false;">-</button>
                <input type="number" id="{{ product.slug }}-more" name="quantity" value="1">
                <button class="btn btn-success" onclick="increaseValue('{{ product.slug }}-more');return false;">+</button>
              </div>
              <div class="row action-more">
                {% if user.is_authenticated and week != 2 and week != 3 %}
                  <div class="submit-act">
                    <input type="submit" value="Добавить в корзину" class="btn btn-outline-success btn-block btn-lg">
                  </div>
                  <div class="submit-act">
                    <button type="button" class="btn btn-outline-success btn-block btn-lg" data-bs-toggle="modal"
                  data-bs-target="#{{ product.slug }}-rate-form" id="{{ product.slug }}-to-rate-button";>
                    <div>Оценить</div>
                    </button>
                  </div>
                {% else %}
                  <div class="submit-act">
                    <button type="button" data-bs-toggle="modal" data-bs-target="#NotAuthorized" 
                    data-bs-dismiss="modal" class="btn btn-outline-success btn-block btn-lg" ;>
                    <div>Добавить в корзину</div>
                    </button>
                  </div>
                  <div class="submit-act">
                    <button type="button" data-bs-toggle="modal" data-bs-target="#NotAuthorized"
                    data-bs-dismiss="modal" class="btn btn-outline-success btn-block btn-lg" ;>
                    <div>Оценить</div>
                    </button>
                  </div>
                {% endif %}
              </div>
            </form>
            <div class="comments-container" style="margin-top: 10px;">
              <div class="comments">
                {% for comment in comments %}
                  {% if comment.product == product %}
                    <div class="comment">
                      <p><strong>{{ comment.user }}</strong>: {{ comment.description }}
                      {{comment.star_rating}}<img src="{% static 'admin\img\star.svg' %}"/></p>
                    </div>
                  {% endif %}
                {% endfor %}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% if user.is_authenticated %}
<div id="{{ product.slug }}-rate-form" class="modal fade">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title">Поделитесь впечатлениями</h1>
      </div>
      <div class="modal-body align-">
        <form action="{% url "shop:comment_view" product.id user.username %}" method="post">
          {% csrf_token %}
          <div class="col flex-column mb-3">
            <p class="d-block">Вкусовые качества</p>
            <div class="row">
              <selection class="rating-area">
                <input type="radio" id="{{ product.slug }}-star-5-a" name="taste-rating" value="5">
                <label for="{{ product.slug }}-star-5-a" title="Отлично"></label>	
                <input type="radio" id="{{ product.slug }}-star-4-a" name="taste-rating" value="4">
                <label for="{{ product.slug }}-star-4-a" title="Хорошо"></label>    
                <input type="radio" id="{{ product.slug }}-star-3-a" name="taste-rating" value="3" checked>
                <label for="{{ product.slug }}-star-3-a" title="Удовлетворительно"></label>  
                <input type="radio" id="{{ product.slug }}-star-2-a" name="taste-rating" value="2">
                <label for="{{ product.slug }}-star-2-a" title="Плохо"></label>    
                <input type="radio" id="{{ product.slug }}-star-1-a" name="taste-rating" value="1">
                <label for="{{ product.slug }}-star-1-a" title="Ужасно"></label>
              <selection/>
            </div>
          </div>
          <div class="col flex-column mb-3">
            <p class="d-block">Внешний вид</p>
            <div class="row">
              <selection class="rating-area">
                <input type="radio" id="{{ product.slug }}-star-5-b" name="representability-rating" value="5">
                <label for="{{ product.slug }}-star-5-b" title="Отлично"></label>	
                <input type="radio" id="{{ product.slug }}-star-4-b" name="representability-rating" value="4">
                <label for="{{ product.slug }}-star-4-b" title="Хорошо"></label>    
                <input type="radio" id="{{ product.slug }}-star-3-b" name="representability-rating" value="3" checked>
                <label for="{{ product.slug }}-star-3-b" title="Удовлетворительно"></label>  
                <input type="radio" id="{{ product.slug }}-star-2-b" name="representability-rating" value="2">
                <label for="{{ product.slug }}-star-2-b" title="Плохо"></label>    
                <input type="radio" id="{{ product.slug }}-star-1-b" name="representability-rating" value="1">
                <label for="{{ product.slug }}-star-1-b" title="Ужасно"></label>
              <selection/>
            </div>
          </div>
          <div class="col flex-column mb-3">
            <p class="d-block">Цена</p>
              <div class="row">
              <selection class="rating-area">
                <input type="radio" id="{{ product.slug }}-star-5-c" name="price-rating" value="5">
                <label for="{{ product.slug }}-star-5-c" title="Отлично"></label>	
                <input type="radio" id="{{ product.slug }}-star-4-c" name="price-rating" value="4">
                <label for="{{ product.slug }}-star-4-c" title="Хорошо"></label>    
                <input type="radio" id="{{ product.slug }}-star-3-c" name="price-rating" value="3" checked>
                <label for="{{ product.slug }}-star-3-c" title="Удовлетворительно"></label>  
                <input type="radio" id="{{ product.slug }}-star-2-c" name="price-rating" value="2">
                <label for="{{ product.slug }}-star-2-c" title="Плохо"></label>    
                <input type="radio" id="{{ product.slug }}-star-1-c" name="price-rating" value="1">
                <label for="{{ product.slug }}-star-1-c" title="Ужасно"></label>
              <selection/>
              </div>
          </div>
          <div class="form-group shadow-textarea mb-3">
            <textarea class="form-control z-depth-1" id="{{ product.slug }}-comment-text" rows="3"
            name="comment-text" placeholder="Ваш комментарий (необязательно)"></textarea>
          </div>
          <div class="col flex-column"> <button type="submit" class="rating-submit-btn">Отправить</button> </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endif %}