cart/urls.py
from django.urls import path

from . views import (
    in_cart_add,
    cart_add, 
    user_order,
    business_detail,
    cart_detail, 
    cart_remove
)

app_name = 'cart'

urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('business_detail/', business_detail, name='business_detail'),
    path('current_orders/', user_order, name='user_order'),
    path('current_orders/<int:order_id>/', user_order, name='user_order_special'),
    path('add/<int:product_id>', in_cart_add, name='in_cart_add'),
    path('add/<int:product_id>/<str:category_slug>', cart_add, name='cart_add'),
    path('remove/<int:product_id>/', cart_remove, name='cart_remove'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

admin.site.site_header = 'Модуль администратора СБЕР кафе'
admin.site.index_title = 'Модуль администратора'
admin.site.site_title = 'СБЕР кафе'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('staff/', include('staff.urls')),
    path('', include('shop.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from .views import order_create, pin_create
 
app_name = 'orders'
 
urlpatterns = [
    path('create/', order_create, name='order_create'),
    path('create/pin_create/', pin_create, name='pin_create'),
]

orders/models.py
from django.db import models
from shop.models import Product, Table
from users.models import Profile
from django.urls import reverse

class Order (models.Model):
    id = models.AutoField(primary_key=True)
    profile = models.ForeignKey(Profile, related_name='order', null=True, blank=True, on_delete=models.CASCADE)
    ready = models.BooleanField(default=False)  # готов ли заказ
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    in_cafe = models.BooleanField(default=False)
    reserve_time = models.CharField(max_length=10, default="13:30")
    table = models.ForeignKey(Table, related_name='table', null=True, blank=True, on_delete=models.CASCADE)

    class Meta:
        ordering = ('-created',)
        verbose_name = 'заказ'
        verbose_name_plural = 'заказы'

    def __str__(self):
        return 'Заказ {}'.format(self.id)

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())
    
    def get_absolute_url(self):
        return reverse('cart:user_order_special', args=[self.id])


class OrderItem(models.Model):
    id = models.AutoField(primary_key=True)
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='order_items', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return '{}'.format(self.id)

    def get_cost(self):
        return self.price * self.quantity

orders/forms.py
from django import forms
from .models import Order

orders/views.py
from django.shortcuts import render
from django.core.mail import send_mail
from django.http import JsonResponse
from django.shortcuts import redirect
from django.contrib import messages
from config.views import get_natural_range
from .models import OrderItem, Order
from cart.cart import Cart
from users.models import Profile 
from shop.models import Table, TableTime, ProductStatistics
import qrcode, random, string


def pin_generator(size=6, chars=string.digits):
    return ''.join(random.choice(chars) for x in range(size))

def pin_create(request):
    if request.method == 'POST':
        phone = request.POST['phone']
        if len(phone) == 16:
            phone = phone.replace('+', '').replace('(', '').replace(')', '').replace('-', '').replace('7', '', 1)
        try:
            profile = Profile.objects.get(phone=phone)
            if profile.user.username != '':
                profile.pincode = pin_generator()
                profile.save()
                response = {
                    'username': profile.name,
                    'pincode': profile.pincode
                }
        except:
            response = {'error': 'Пользователь не найден'}
    return JsonResponse(response)


def order_create(request):
    cart = Cart(request)
    profile = request.user.profile
    profile = Profile.objects.get(email=request.user.username)
    if request.method == 'POST':
        order = Order.objects.create()
        time = 0
        if not int(request.POST['chosenTableId']):
            order.in_cafe = False
        else:
            order.in_cafe = True
            table = Table.objects.get(id=request.POST['chosenTableId'])
            order.table = table
            time = request.POST['chosenTableTime']
            order.reserve_time = time
            table.order_id = order.id
            table_time = TableTime.objects.create(table_id=table.id, ordered_at=time)
            table.save()
        order.profile = profile
        order.save()
        profile.rating += 1
        data = {'order': 0, 'profile': 0}
        for item in cart:
            if time:
              print(int(item['quantity']))
              try:
                  product_stat = ProductStatistics.objects.get(product=item['product'])
              except:
                  product_stat  = ProductStatistics.objects.create(product=item['product'])
              if time < "11:59":
                  product_stat.morning = int(product_stat.morning) + int(item['quantity'])
              elif time < "17:59":
                  product_stat.afternoon = int(product_stat.afternoon) + int(item['quantity'])
              else:
                  product_stat.evening = int(product_stat.evening) + int(item['quantity'])
              product_stat.total = int(product_stat.total) + int(item['quantity'])
              product_stat.save() 

            OrderItem.objects.create(
                order = order,
                product = item['product'],
                price = item['price'],
                quantity = item['quantity']
            )
        profile.balance -= order.get_total_cost()
        profile.save()
        data['order'] = order
        data['profile'] = profile
        img = qrcode.make(data)
        img.save("media/qr/" + str(order.id) + ".png")
        cart.clear()
        send_mail(
            'Заказ Оформлен', 
            'Войдите в админ панель, что бы просмотреть новый заказ.' , 
            'info@it-cube.krk', 
            ['manager@it-cube.krk'], 
            fail_silently=False
        )
    return redirect('shop:product_list')

orders/templates/orders/order/create.html
{% load static %}
<!-- Modal -->
<div id="orderConfirm" class="modal fade">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
          <h5 class="modal-title">Подтверждение заказа</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
      </div>

      <script>
        
        function toggleActiveState(button) {
          document.getElementById('occupy-button').classList.add('hidden')
          // Удаляем класс активности у всех кнопок
          var buttons = document.getElementsByClassName('btn');
          for (var i = 0; i < buttons.length; i++) {
            buttons[i].classList.remove('btn-active');
            // Добавляем класс неактивности ко всем кнопкам
            buttons[i].classList.add('btn-inactive');
          }
        
          // Добавляем класс активности только кнопке, которая была нажата
          button.classList.remove('btn-inactive');
          button.classList.add('btn-active');
        }

        function makeTablesVisible() {
          document.getElementById('occupy-button').hidden=false;
          document.getElementById('chosenTableNumber').hidden=false;
          document.getElementById('chosenTableTime').hidden=false;
          
        }
        function makeTablesHidden() {
          document.getElementById('chosenTableId').value=0;
          document.getElementById('occupy-button').hidden=true;
          document.getElementById('chosenTableNumber').hidden=true;
          document.getElementById('chosenTableTime').hidden=true;
        }
      </script>
      <style>
        .btn-active {
        background-color: green;
        color: white;
        }   
      </style>
      


      <div class="page-header">
        Заказ
      </div>
      <li class="list-group-item active"><div class="total-cost"> Общая стоимость: {{ cart.get_total_price }} ₽</div></li>
      <div class="container-placement">
        <button type="button" class="btn btn-outline-success btn-block" onclick="toggleActiveState(this);makeTablesVisible()" style="margin-right: 15%;">
          Забронировать столик
        </button>
        <button type="button" class="btn btn-outline-success btn-block" onclick="toggleActiveState(this);makeTablesHidden()">
          Забрать с собой
        </button>
      </div>
      <form role="form" method="POST" action="{% url "orders:order_create" %}" id="apply-form">
        {% csrf_token %}
        <div class="container-placement"> 
          <button type="button" class="btn btn-outline-info btn-block" data-bs-toggle="modal"
            data-bs-target="#TableOccupation" id="occupy-button" style="margin-right: 5%; font-size: 14pt;" hidden>
            <div>Выбрать столик</div>
          </button>
          <input class="cool-input" type="number" id="chosenTableId" name="chosenTableId" value="0" hidden>
          <input class="cool-input" type="number" id="chosenTableNumber" name="chosenTableNumber" placeholder="Номер" hidden readonly>
          <input class="cool-input" type="time" id="chosenTableTime" name="chosenTableTime" style="margin-left: 5%;" hidden readonly>
        </div>
        <div class="col p-2">
          <button type="submit" class="btn btn-outline-warning btn-block btn-lg">Оформить заказ</button>
        </div>
      </form>
      <button class="btn btn-warning btn-block" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
        <div class="check-title">Показать чек</div>
      </button>
      <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
        {% if business is None %}
          {% for item in cart %}
            <li><div class="dropdown-item" >{{ item.quantity }} x {{ item.product.name }} {{ item.total_price }} ₽</div></li>
          {% endfor %}
        {% else %}
          {% for item in cart %}
            <li><div class="dropdown-item" >{{ item.name }}</div></li>
          {% endfor %}
        {% endif %}
      </ul>
                
    </div>
  </div>
</div>

{% include 'shop\product\table_occupation.html'%}

orders/templates/orders/order/created.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<div id="content" class="p-4 p-md-5">
    <div class="album py-5">
        <div class="container">
            <div class="row" style="margin-top: 6%">
                <div class="col-md-8 col-md-offset-2">
                    <h3 class="page-header">Приятного аппетита, {{ profile.name }}!</h3>
                    <p>Ваш заказ оформлен. Номер заказа <strong>{{ order.id }}</strong>.</p>
                    <p>Ваш рейтинг<strong>{{ profile.rating }}</strong>.</p>
                    {% if qr_image %}
                    <p>QR код для оплаты:</p>
                    <img src="/media/qr/{{ order.id }}.png">
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}