cart/urls.py
from django.urls import path

from . views import (
    in_cart_add,
    cart_add, 
    user_order,
    business_detail,
    cart_detail, 
    cart_remove
)

app_name = 'cart'

urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('business_detail/', business_detail, name='business_detail'),
    path('current_orders/', user_order, name='user_order'),
    path('current_orders/<int:order_id>/', user_order, name='user_order_special'),
    path('add/<int:product_id>', in_cart_add, name='in_cart_add'),
    path('add/<int:product_id>/<str:category_slug>', cart_add, name='cart_add'),
    path('remove/<int:product_id>/', cart_remove, name='cart_remove'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

admin.site.site_header = 'Модуль администратора СБЕР кафе'
admin.site.index_title = 'Модуль администратора'
admin.site.site_title = 'СБЕР кафе'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('staff/', include('staff.urls')),
    path('', include('shop.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.contrib import admin
from django.urls import path

from shop.views import (
    product_list, 
    product_detail,
    about_us,
    lunch,
    lunch_products, 
    logout_view,
    comment_add,
    get_table,
    tables_by_time,
)
from .views import *

app_name = 'shop'

urlpatterns = [
    path('', product_list, name='product_list'),
    path('logout/', logout_view, name='logout_view'),
    path('lunch/<int:day>/', lunch, name="lunch"),
    path('lunch_products/', lunch_products, name="lunch_products"),
    path('about_us/', about_us, name='about_us'),
    path('print_us/', print_us, name='print_us'),
    path('get_table/', get_table, name='get_table'),
    path('tables_by_time/', tables_by_time, name=''),
    path('<str:category_slug>/<int:week>', product_list, name='product_list_by_category'),
    path('<int:id>/<str:slug>/', product_detail, name='product_detail'),
    path('comment/<int:product_id>/<str:username>/', comment_add, name='comment_view'),
]

staff/urls.py
from django.urls import path
from .views import (edit_product, add_product, login, set_tables, ProductDeleteView, order_is_applied,
                     product, pending_orders, ready_orders, table_list, logout_view, order_is_ready, statistics)
from django.views.generic import RedirectView
from .views import ProductDeleteView
from .views import ProductDetailView
from .views import (edit_product, add_product, login, manage_panel, set_tables,
                     product, pending_orders, ready_orders, table_list, logout_view, order_is_ready, order_is_applied)
from django.views.generic import RedirectView
from .views import delete, deleter, deleteus
from .views import ProductDetailView, manage_panel3, reviews
from shop.views import manage_us, print_us

app_name = 'staff'

urlpatterns = [
    path('pending_orders/', pending_orders, name='pending_orders'),
    path('ready_orders/', ready_orders, name='ready_orders'),

    path('manage_panel3/', manage_panel3, name='manage_panel3'),
    path('reviews/', reviews, name='reviews'),
    path('reviews/delete/<int:id>', deleter, name='reviews_delete'),
    path('manage_us/delete/<int:id>', deleteus, name='deleteus'),
    path('manage_us/', manage_us, name='manage_us'),

    path('order_is_ready/<int:id>', order_is_ready, name='order_is_ready'),
    path('order_is_applied/<int:id>', order_is_applied, name='order_is_applied'),

    path('product/', product, name='product'),
    path('product/<int:id>/delete/', delete, name='product_delete'),
    path('product/<int:id>/<slug:slug>/', ProductDetailView.as_view(), name='product_detail'),
    path('edit_product/<int:product_id>/', edit_product, name='edit_product'),
    path('add_product/', add_product, name='add_product'),

    path('set_tables/', set_tables, name='set_tables'),
    path('table_list/', table_list, name='table_list'),

    path('statistics/<int:category>/<int:day_time>', statistics, name='statistics'),
    path('manage_panel/', manage_panel, name='manage_panel'),
    path('login/', login, name='login'),
    path('logout/', logout_view, name='logout_view')
]

staff/models.py
from django.db import models

from django.contrib.auth.hashers import make_password
from shop.models import Product
from shop.models import Category, Comment
from django.contrib.auth.models import User
import uuid, os
    

class Staff(models.Model):
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True, unique=True)
    password = models.TextField()
    staff_id = models.IntegerField()
    logged = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        if len(self.password) < 60:
            self.password = make_password(self.password)
        
        super().save(*args, **kwargs)


class StaffProduct(models.Model):
    id = models.AutoField(primary_key=True)
    available = models.BooleanField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.TextField()
    slug = models.SlugField(max_length=100, db_index=True)
    name = models.CharField(max_length=100, db_index=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    original_product = models.OneToOneField(Product, on_delete=models.CASCADE)

    # Добавь другие необходимые поля для модели StaffProduct

    def __str__(self):
        return self.name
    
    

staff/forms.py
from django import forms
from .models import Product
from shop.models import Product, Comment, CommentManage
from shop.forms import CommentForm

class LoginForm(forms.Form):
    email = forms.EmailField(label='Email')
    password = forms.CharField(label='Password', widget=forms.PasswordInput)


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'price', 'category', 'stock', 'description', 'available', 'week', 'clpc', 'star_rating', 'image']
        widgets = {
            'star_rating': forms.HiddenInput(),
            }
        labels = {
            'name': 'Имя',
            'price': 'Цена',
            'category': 'Категория',
            'stock': 'Кол-во',
            'description': 'Описание',
            'available': 'Доступен ли',
            'week': 'Неделя',
            'clpc': 'КБЖУ',
            'image': 'Изображение',
        }

staff/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.hashers import check_password
from django.contrib import messages
from django.urls import reverse
from django.views import View
from django.views.generic import DeleteView
from django.urls import reverse_lazy
from django.contrib.auth.hashers import make_password
from staff.models import Staff
from orders.models import Order
from shop.models import Product, Table, Cafeteria, ProductStatistics, Category
from .forms import ProductForm
from config.views import get_natural_range
import json
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.hashers import check_password
from django.contrib import messages
from django.http import HttpResponseNotFound 
from django.urls import reverse
from django.views import View
from django.views.generic import DeleteView
from django.urls import reverse_lazy
from django.contrib.auth.hashers import make_password
from staff.models import Staff
from orders.models import Order
from shop.models import Product, Table, Cafeteria, Comment
from shop.models import *
from .forms import ProductForm, CommentForm
from shop.forms import CommentForm
from config.views import get_natural_range
import json
from django.http import HttpResponse
from transliterate import translit


def check_login(request):
    user_id = request.user.id
    staff = get_object_or_404(Staff, user_id=user_id)
    if staff.logged:
        return True
    return False


def login(request):
    user_id = request.user.id
    staff = get_object_or_404(Staff, user_id=user_id)

    if staff.logged:
        return redirect(reverse('staff:manage_panel'))

    err = ""

    if request.method == 'POST':
        user_password = request.POST.get('password')

        if check_password(user_password, staff.password):
            staff.logged = True
            staff.save()

            if staff.staff_id == 1 or staff.staff_id == 2:
                return redirect(reverse('staff:manage_panel'))
                print('1, 2')
            elif staff.staff_id == 3:
                return redirect(reverse('staff:manage_panel3'))
                print('3')
            else:
                err = f"Unknown staff_id: {staff.staff_id}"

        else:
            err = "Неверный пароль"

    return render(request, 'staff/login.html', {"error": err})

def pending_orders(request):
    if not check_login(request):
       return redirect(reverse("staff:login"))
    orders = Order.objects.filter(ready=False).order_by('reserve_time', 'id')
    return render(request, 'staff/pending_orders.html', {'orders': orders})

# связь с pending
def order_is_ready(request, id):
    order = Order.objects.get(id=id)
    order.ready = True
    order.save()
    return redirect(reverse("staff:pending_orders"))


def ready_orders(request):
    if not check_login(request):
       return redirect(reverse("staff:login"))
    orders = Order.objects.filter(ready=True).order_by('reserve_time', 'id')
    return render(request, 'staff/ready_orders.html', {'orders': orders})


# связь с ready
def order_is_applied(request, id):
    order = Order.objects.get(id=id)
    order.delete()
    return redirect(reverse("staff:ready_orders"))

    
def product(request):
    if not check_login(request):
        return redirect(reverse("staff:login"))
    products = Product.objects.all().order_by('id')
    return render(request, 'staff/manage_pl.html', {'products': products})


def add_product(request):
    if not check_login(request):
       return redirect(reverse("staff:login"))
    if request.method == 'POST':
        form = ProductForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('staff:login'))
    else:
        form = ProductForm()
    return render(request, 'staff/add_product.html', {'form': form})


def edit_product(request, product_id):
    if not check_login(request):
       return redirect(reverse("staff:login"))
    product = get_object_or_404(Product, id=product_id)
    if request.method == 'POST':
        form = ProductForm(request.POST, instance=product)
        if form.is_valid():
            form.save()
            return redirect(reverse('staff:login'))
    else:
        form = ProductForm(instance=product)
    return render(request, 'staff/edit_product.html', {'form': form, 'product': product})


def table_list(request):
    if not check_login(request):
        return redirect(reverse("staff:login"))
    cafeteria = Cafeteria.objects.get(id=3)
    if request.method == "POST":
        cafe_rows, cafe_cols = request.POST.get("cafe_rows"), request.POST.get("cafe_cols")
        cafeteria.rows = int(cafe_rows)
        cafeteria.cols = int(cafe_cols)
        cafeteria.save()
    tables = Table.objects.filter(cafeteria_id=3)
    context = {
        "tables": tables,
        "cafeteria": cafeteria,
    }
    return render(request, 'staff/edit_tables.html', context)

def set_tables(request):
    if not check_login(request):
        return redirect(reverse("staff:login"))
    if request.method == 'POST':
        data = json.loads(request.body)
        selected_seats = list(map(int, data['selectedSeats']))
        action = data.get('action')
        tables = Table.objects.filter(id__in=selected_seats)
        if action == "HIDE":
            for table in tables:
                table.hidden = True
                table.save()
        else:
            for table in tables:
                table.hidden = False
                table.save()
    return redirect(reverse('staff:table_list'))


def statistics(request, category=0, day_time=0):
    initial = ProductStatistics.objects.all()
    if category:
        initial = initial.filter(product__category_id=category)
    if day_time == 1:
        statistics = initial.order_by('-morning')
    elif day_time == 2:
        statistics = initial.order_by('-afternoon')
    elif day_time == 3:
        statistics = initial.order_by('-evening')
    else:
        statistics = initial.order_by('-total')
    day_times = [[i, el] for i, el in enumerate(['Общие', 'Утром', 'Днем', 'Вечером'])]
    categories = Category.objects.all()
    context = {'statistics': statistics, 'categories': categories, 'day_times': day_times,
               'cur_category': category, 'cur_day_time': day_time,}
    return render(request, 'staff/statistics.html', context)


def manage_panel(request):
    if not check_login(request):
       return redirect(reverse("staff:login"))
    return render(request, 'staff/choose_category.html')

def logout_view(request):
    user_id = request.user.id
    try:
        staff = get_object_or_404(Staff, user_id=user_id)
        staff.logged = False
        staff.save()
    except:
        pass
    return redirect('shop:product_list')


class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy('login/')  
 

class ProductDetailView(View):
    def get(self, request, id, slug):
        product = get_object_or_404(Product, id=id, slug=slug)

    def get(self, request, id, slug):
        product = get_object_or_404(Product, id=id, slug=slug)
        return render(request, self.template_name, {'product': product})

def delete(request, id):
    try:
        product = Product.objects.get(id=id)
        product.delete()
        return redirect(reverse('staff:product')) 
    except Product.DoesNotExist:
        return HttpResponseNotFound("<h2>Запись не найдена</h2>")


def manage_panel3(request):
    if not check_login(request):
       return redirect(reverse("staff:login"))
    return render(request, 'staff/choose_category3.html')

def reviews(request):
    if not check_login(request):
       return redirect(reverse("staff:login"))
    
    comments = Comment.objects.all()

    # Обработка отправки формы
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            # Сохраняем комментарий в базе данных
            form.save()
            # Перенаправляем на страницу обзора комментариев
            return redirect('staff:reviews')
    else:
        # Если это GET-запрос, создаем пустую форму
        form = CommentForm()

    return render(request, 'staff/reviews_panel.html', {'comments': comments, 'form': form})

def deleter(request, id):
    try:
        comment = Comment.objects.get(id=id)
        comment.delete()
        return redirect(reverse('staff:reviews')) 
    except Product.DoesNotExist:
        return HttpResponseNotFound("<h2>Запись не найдена</h2>")

def deleteus(request, id):
    try:
        comment = get_object_or_404(CommentManage, id=id)
        comment.delete()
        return redirect(reverse('staff:manage_us')) 
    except CommentManage.DoesNotExist:
        return HttpResponseNotFound("<h2>Запись не найдена</h2>")

staff/templates/staff/choose_category.html
<!doctype html>
<html lang="ru">

<head>
  {% load static %}
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" 
  integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css\main.css' %}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/prefixfree/1.0.7/prefixfree.min.js"></script>
  <title>СБЕР Кафе</title>
  
</head>

<body>
  <div class="container" height:100%;>
    <header class="navigator-bar" id="navbar">
      <div class="left">
        <div class="col">
          <a class="navbar-brand " href="/">
            <img src="{% static 'image/logo.png' %}" width="100" height="100" alt="">
          </a>
        </div>
        <div class="navbar-col">
          <a class="navbar-brand" href="{% url 'shop:product_list' %}">Меню</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
            aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Переключатель навигации">
            <span class="navbar-toggler-icon"></span>
          </button>
        </div>
        <div class="navbar-col">
          <a class="navbar-brand" href="{% url "shop:about_us" %}">О нас</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
            aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Переключатель навигации">
            <span class="navbar-toggler-icon"></span>
          </button>
        </div>
      </div>
      
      {% if user.is_authenticated %}
      <div class="col" style="justify-content: center; align-items: center; margin-top: 10px;">
        <div class="greetings-label"> <label class="control-label"> Добро пожаловать, {{user.username}}!</label> </div>
      </div>
      <div class="col" style="justify-content: end;">
        <button type="button" class="btn btn-light">
          <a href="{% url "staff:logout_view" %}" class="user-login" style="text-decoration: none; color: inherit;">Выход с менедж-панели</a>
        </button>
      </div>
      <div class="col" style="justify-content: end;">
        <button type="button" class="btn btn-light">
          <a href="{% url "shop:logout_view" %}" class="user-login" style="text-decoration: none; color: inherit;">Выйти</a>
        </button>
      </div>
      {% else %}
      <div class="col-4">
        <button type="button" class="btn btn-light" style="margin-left: 78%" data-bs-toggle="modal"
          data-bs-target="#ModalLoginForm" id="entry-button" ;>
          <div class="user-login">Войти</div>
        </button>
      </div>
      {% endif %}
      {% include 'shop\product\authorization.html' %}
    </header>
    
  {% include 'shop\product\not_authorized.html' %}
  
    <div class="choose-category">
        <a class="btn btn-success mb-2" href="{% url 'staff:pending_orders' %}">Входящие заказы</a>
        <a class="btn btn-success mb-2" href="{% url 'staff:ready_orders' %}">Готовые заказы</a>
        <a class="btn btn-success mb-2" href="{% url 'staff:product' %}">Продукты</a>
        <a class="btn btn-success mb-2" href="{% url 'staff:table_list' %}">Столы</a>
        <a class="btn btn-success mb-2" href="{% url 'staff:statistics' category=0 day_time=0 %}">Статистика</a>
    </div>

  {% block content %} 

  {% endblock %}
  <!-- jquery-->
  <script src="https://code.jquery.com/jquery-3.3.1.min.js"
    integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
   
</body>

</html>
    

staff/templates/staff/manage_us.html
<!doctype html>
<html lang="ru">

<head>
  {% load static %}
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" 
  integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css\main.css' %}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/prefixfree/1.0.7/prefixfree.min.js"></script>
  <title>СБЕР Кафе</title>
  
</head>

<body>
  <div class="container" height:100%;>
    <header class="navigator-bar" id="navbar">
      <div class="left">
        <div class="col">
          <a class="navbar-brand " href="/">
            <img src="{% static 'image/logo.png' %}" width="100" height="100" alt="">
          </a>
        </div>
        <div class="navbar-col">
          <a class="navbar-brand" href="{% url 'shop:product_list' %}">Меню</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
            aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Переключатель навигации">
            <span class="navbar-toggler-icon"></span>
          </button>
        </div>
        <div class="navbar-col">
          <a class="navbar-brand" href="{% url "shop:about_us" %}">О нас</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
            aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Переключатель навигации">
            <span class="navbar-toggler-icon"></span>
          </button>
        </div>
      </div>
      
      {% if user.is_authenticated %}
      <div class="col" style="justify-content: center; align-items: center; margin-top: 10px;">
        <div class="greetings-label"> <label class="control-label"> Добро пожаловать, {{user.username}}!</label> </div>
      </div>
      <div class="col" style="justify-content: end;">
        <button type="button" class="btn btn-light">
          <a href="{% url "staff:logout_view" %}" class="user-login" style="text-decoration: none; color: inherit;">Выход с менедж-панели</a>
        </button>
      </div>
      <div class="col" style="justify-content: end;">
        <button type="button" class="btn btn-light">
          <a href="{% url "shop:logout_view" %}" class="user-login" style="text-decoration: none; color: inherit;">Выйти</a>
        </button>
      </div>
      {% else %}
      <div class="col-4">
        <button type="button" class="btn btn-light" style="margin-left: 78%" data-bs-toggle="modal"
          data-bs-target="#ModalLoginForm" id="entry-button" ;>
          <div class="user-login">Войти</div>
        </button>
      </div>
      {% endif %}
      {% include 'shop\product\authorization.html' %}
    </header>
    
  {% include 'shop\product\not_authorized.html' %}
  
    <div class="choose-category">
        <div class="choose-category-title">Выберите:</div>
        <a class="btn btn-success btn-choose-category" href="{% url 'staff:reviews' %}">Отзывы</a>
        <a class="btn btn-success btn-choose-category" href="{% url 'staff:manage_us' %}">обращения к Менеджеру</a>
        </div>
    </div>


  <div class="wrapper d-flex align-items-stretch">
    <div class="container">
      <div class="table-responsive">
        <table class="table">
          <thead>
            <tr>
              <th>ID</th>
              <th>Пользователь</th>
              <th>Описание</th>
              <th>Удалить</th>
            </tr>
          </thead>
          <tbody>
            {% for comment in comments %}
            <tr>
              <td>{{ comment.id }}</td>
              <td>{{ comment.user }}</td>
              <td>{{ comment.description }}</td>
              <td><a href="{% url 'staff:deleteus' id=comment.id %}">Удалить</a></td>

            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
      
  </div>
  <!-- jquery-->
  <script src="https://code.jquery.com/jquery-3.3.1.min.js"
    integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
   
</body>

</html>

staff/templates/staff/reviews_panel.html
<!doctype html>
<html lang="ru">

<head>
  {% load static %}
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" 
  integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css\main.css' %}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/prefixfree/1.0.7/prefixfree.min.js"></script>
  <title>СБЕР Кафе</title>
  
</head>

<body>
  <div class="container" height:100%;>
    <header class="navigator-bar" id="navbar">
      <div class="left">
        <div class="col">
          <a class="navbar-brand " href="/">
            <img src="{% static 'image/logo.png' %}" width="100" height="100" alt="">
          </a>
        </div>
        <div class="navbar-col">
          <a class="navbar-brand" href="{% url 'shop:product_list' %}">Меню</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
            aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Переключатель навигации">
            <span class="navbar-toggler-icon"></span>
          </button>
        </div>
        <div class="navbar-col">
          <a class="navbar-brand" href="{% url "shop:about_us" %}">О нас</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
            aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Переключатель навигации">
            <span class="navbar-toggler-icon"></span>
          </button>
        </div>
      </div>
      
      {% if user.is_authenticated %}
      <div class="col" style="justify-content: center; align-items: center; margin-top: 10px;">
        <div class="greetings-label"> <label class="control-label"> Добро пожаловать, {{user.username}}!</label> </div>
      </div>
      <div class="col" style="justify-content: end;">
        <button type="button" class="btn btn-light">
          <a href="{% url "staff:logout_view" %}" class="user-login" style="text-decoration: none; color: inherit;">Выход с менедж-панели</a>
        </button>
      </div>
      <div class="col" style="justify-content: end;">
        <button type="button" class="btn btn-light">
          <a href="{% url "shop:logout_view" %}" class="user-login" style="text-decoration: none; color: inherit;">Выйти</a>
        </button>
      </div>
      {% else %}
      <div class="col-4">
        <button type="button" class="btn btn-light" style="margin-left: 78%" data-bs-toggle="modal"
          data-bs-target="#ModalLoginForm" id="entry-button" ;>
          <div class="user-login">Войти</div>
        </button>
      </div>
      {% endif %}
      {% include 'shop\product\authorization.html' %}
    </header>
    
  {% include 'shop\product\not_authorized.html' %}
  
    <div class="choose-category">
        <div class="choose-category-title">Выберите:</div>
        <a class="btn btn-success btn-choose-category" href="{% url 'staff:reviews' %}">Отзывы</a>
        <a class="btn btn-success btn-choose-category" href="{% url 'staff:manage_us' %}">обращения к Менеджеру</a>
        </div>
    </div>


  <div class="wrapper d-flex align-items-stretch">
    <div class="container">
      <div class="table-responsive">
        <table class="table">
          <thead>
            <tr>
              <th>ID</th>
              <th>Пользователь</th>
              <th>Дата Создания</th>
              <th>Рейтинг</th>
              <th>Описание</th>
              <th>Продукт</th>
              <th>Продукт ID</th>
              <th>Удалить</th>
            </tr>
          </thead>
          <tbody>
            {% for comment in comments %}
            <tr>
              <td>{{ comment.id }}</td>
              <td>{{ comment.user }}</td>
              <td>{{ comment.written_at }}</td>
              <td>{{ comment.star_rating }}</td>
              <td>{{ comment.description }}</td>
              <td>{{ comment.product.name }}</td>
              <td>{{ comment.product_id }}</td>
              <td><a href="{% url 'staff:reviews_delete' id=comment.id %}">Удалить</a></td>
            

            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
      
  </div>
  <!-- jquery-->
  <script src="https://code.jquery.com/jquery-3.3.1.min.js"
    integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
   
</body>

</html>